"""empty message

Revision ID: 728cdc474139
Revises: 4c322d2b56f5
Create Date: 2023-06-05 18:07:24.610569

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '728cdc474139'
down_revision = '4c322d2b56f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('balance', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_account_user_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_account'))
    )
    with op.batch_alter_table('deposit', schema=None) as batch_op:
        batch_op.add_column(sa.Column('account_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('fk_deposit_user_id', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_deposit_account_id'), 'account', ['account_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('withdraw', schema=None) as batch_op:
        batch_op.add_column(sa.Column('account_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('fk_withdraw_user_id', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_withdraw_account_id'), 'account', ['account_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('withdraw', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), server_default=sa.text("'1'"), nullable=False))
        batch_op.drop_constraint(batch_op.f('fk_withdraw_account_id'), type_='foreignkey')
        batch_op.create_foreign_key('fk_withdraw_user_id', 'user', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('account_id')

    with op.batch_alter_table('deposit', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), server_default=sa.text("'1'"), nullable=False))
        batch_op.drop_constraint(batch_op.f('fk_deposit_account_id'), type_='foreignkey')
        batch_op.create_foreign_key('fk_deposit_user_id', 'user', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('account_id')

    op.drop_table('account')
    # ### end Alembic commands ###
