"""empty message

Revision ID: 9aceb4eba082
Revises: 1a89e4885dbf
Create Date: 2023-06-04 00:17:43.179213

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9aceb4eba082'
down_revision = '1a89e4885dbf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('balance', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('create_date_deposit', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('create_date_withdraw', sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('create_date_withdraw')
        batch_op.drop_column('create_date_deposit')
        batch_op.drop_column('balance')

    # ### end Alembic commands ###
