"""empty message

Revision ID: ba2ba7c63527
Revises: 728cdc474139
Create Date: 2023-06-05 20:27:35.333424

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba2ba7c63527'
down_revision = '728cdc474139'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('account')
    with op.batch_alter_table('deposit', schema=None) as batch_op:
        batch_op.drop_constraint('fk_deposit_account_id', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_deposit_account_id'), 'user', ['account_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('timestamp')

    with op.batch_alter_table('withdraw', schema=None) as batch_op:
        batch_op.drop_constraint('fk_withdraw_account_id', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_withdraw_account_id'), 'user', ['account_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('timestamp')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('withdraw', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', sa.DATETIME(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_withdraw_account_id'), type_='foreignkey')
        batch_op.create_foreign_key('fk_withdraw_account_id', 'account', ['account_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('deposit', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', sa.DATETIME(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_deposit_account_id'), type_='foreignkey')
        batch_op.create_foreign_key('fk_deposit_account_id', 'account', ['account_id'], ['id'], ondelete='CASCADE')

    op.create_table('account',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('balance', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_account_user_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='pk_account')
    )
    # ### end Alembic commands ###
